### ISSUE TITLE
输入图片大小

### ISSUE THREAD

**Issue by hitxujian** [JackEasson/SLPNet_pytorch#3]
您好：
感谢分享！
我有个问题需要请教下：
既然 检测网络的输入是512，为何在default_image_preprocess（）函数 resize到1024而不是直接resize到 512呢？
多谢

**Comment by JackEasson** [comment]
你好，因为车派识别框架设计车牌检测与识别两个任务，过程是先进行车牌检测，输入尺寸是512，检测出的车牌位置信息会映射到大图，即在1024尺寸的图中取出对应的车牌区域来做车牌识别。因此可以看Readme中的系统框架图，整体图像初步resize为1024，对于检测部分输入再次resize为512.
