### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 32: invalid continuation byte

### ISSUE THREAD

**Issue by a741419244** [JackEasson/SLPNet_pytorch#6]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 32: invalid continuation byte 
How to deal with?

**Comment by JackEasson** [comment]
I want to know which line you got this error. Perhaps when you generate the labels (those txt), you didn't use 'utf-8' code type. I did use 'utf-8' to decode the label txts.
