### ISSUE TITLE
关于生成label的问题

### ISSUE THREAD

**Issue by hj812326135** [JackEasson/SLPNet_pytorch#8]
您好，我想问一下，制作数据集的时候是直接根据image的名字生成label的吗，有没有代码处理流程；还有就是示例中的label为什么和名字里对应的坐标数字不一样

**Comment by JackEasson** [comment]
你好，数据图像来源CCPD数据集，但是SLPNet使用的是角点回归方法完成检测任务（具体看论文），所以需要按顺时针标注车牌的四个角点，原始标注仅是bbox，没有用。标注自己用opencv写一个或者使用Labelme都可以。

**Comment by hj812326135** [comment]
感谢回复，我看CCPD数据集里边图片的名字不是有四个角点的信息么(图片名字里用分隔符'-'分开的)。你的数据集都是自己标注的吗？还有我看示例代码里边的四个角点信息也不是按顺时针写的，如果要写的话需要从哪个顶点开始顺时针标注。还有就是不按顺时针标注的话对结果有影响吗？
最后说一下，代码很棒！

**Comment by JackEasson** [comment]
谢谢，关于你的两个问题：
1.首先，CCPD提供的角点信息标注的是车牌中字符串的位置，与车牌角点还是有出入的，所以需要自己标注；
2.必须要顺时针，这个顺序涉及损失计算与后续结果解析的多个环节，所以一定要对应顺序，从左上角开始作为第一个角点，顺时针标注即可。

**Comment by hj812326135** [comment]
好的明白了，十分感谢！儿童节快乐~
